### ISSUE TITLE
Twedit CC3D project -> Save CC3D project (and shortcut ctrl+shift+D) is not working 

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#261] opened 2020-06-18 19:23 UTC

**Comment by JulianoGianlupi** [comment] 2020-06-18 19:40
Or worse, it works and then borks the global sqlite settings file

**Comment by CompuCell3D** [comment] 2020-06-20 21:04
what is the context that this feature is not working? How have you changed the project and then attempted to save it?

**Comment by JulianoGianlupi** [comment] 2020-06-22 13:43
When changing a file in the project using the save project doesn't save that file. If this was just a mistake on intended use we can close the issue, but I think we should make the intended use clearer somehow.

**Comment by CompuCell3D** [comment] 2020-07-24 23:25
Juliano, I am closing this issue. I could not reproduce it. If you are able to reproduce steps that demonstrate this issue again, please reopen

**Closed by CompuCell3D** 2020-07-24 23:25 UTC
Labels: Twedit++, bug
