### ISSUE TITLE
PolygonInitializer does not work in 2D

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#736] opened 2024-07-23 21:48 UTC
The PolygonInitializer does not work in **2D** unless you specify an &lt;extrude **zMax="5"** zMin="0"/&gt; with a zMax at least as big as the cell &lt;width&gt; value.

In a 2D model, with &lt;extrude **zMax="1"** zMin="0"/&gt; and &lt;Width&gt;1&lt;/Width&gt; you get
![image](https://github.com/user-attachments/assets/053d8039-00c4-417f-b969-34fe6797d0c7)

In the same model with &lt;Width&gt;2&lt;/Width&gt;you get
![image](https://github.com/user-attachments/assets/3fca860b-c351-4db1-ba89-8882bf47f467)

If you increase the PolygonInitializer's &lt;extrude&gt; value (even though the model is 2D) to be at least as big as the cell &lt;width&gt; then it seems to work correctly.

&lt;Extrude zMax="5" zMin="0"/&gt;
          &lt;Width>5</Width&gt;

The Potts block
   &lt;Potts&gt;
      &lt;Dimensions x="100" y="100" z="1"/&gt;
      &lt;Steps>10001&lt;/Steps&gt;
      &lt;Temperature&gt;10.0&lt;/Temperature&gt;
      &lt;NeighborOrder&gt;3&lt;/NeighborOrder&gt;
   &lt;/Potts>

**Comment by fyffep** [comment] 2024-07-28 19:00
The cells are merely "hidden" since VTK only looks at one slice of the screen in 3D. In reality, the cells are being placed at the wrong z-index. It is not my proudest feature, so I am not surprised if there are further bugs. Nonetheless, this one _should_ be easy to fix.

**Comment by jpsluka** [comment] 2024-07-28 19:48
No they are not hidden they do not exist. CC3D's inventory says there are no cells. Attached is a zip of a 2D model. The  `<Extrude zMax="5" zMin="0"/>` the `xMax ` has to be at least as big as the cell width otherwise no cells are created (see line 40 in the xml).
[PolygonInitializer_demo.zip](https://github.com/user-attachments/files/16405017/PolygonInitializer_demo.zip)

**Comment by fyffep** [comment] 2024-07-28 20:19
Ah, you are correct. This is the expected behavior. zMax must be at least as big as the cell width. You are justified in raising this issue. It's probably confusing and could be changed so that at least 1 layer of cells will always be generated.

**Comment by jpsluka** [comment] 2024-07-28 20:44
The code should just check to see if it is a 2D model, and if it is not, only then check if the Z dim is big enough for the cell width.

**Comment by maciekswat** [comment] 2024-09-28 19:16
@fyffep can we close it?

**Closed** 2024-10-03 01:14 UTC
