### ISSUE TITLE
Nonsensical file at e.g.,  C:\Users\<USERNAME>\.compucell3d_py3\_settings.sqlite 

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#223] opened 2020-03-24 21:06 UTC
The _settings.sqlite file created in the directory C:/Users/{USERNAME}/.compucell3d_py3/ should not exist. It makes no sense for a new simulation to default to an sqlite file that was used for the last, possibly completely unrelated, simulation. 

The only sqlite file should be the one in the Project's Simulation directory. For a new project the one in the distribution at;
   C:/CompuCell3D-py3-64bit/lib/site-packages/cc3d/player5/Configuration_settings/_settings.sqlite
can be the default but it must be very "vanilla".

Windows 10, cc3d 4.1.1

**Comment by CompuCell3D** [comment] 2020-03-24 21:19
Nope, this is by design . The file is not nonsensical. It actually contains the following:
a) initial default settings for simulation that has not been run
b) global settings e.g. list of recently run simulations that cannot be stored locally.
c) while the name of the file is the same as the one stored in local simulation folder the file has different content and serves different purpose

Let me know if this makes sense

**Comment by jpsluka** [comment] 2020-03-24 21:28
In any case, nuking it appears to fix the problem with simulations with fields. Also, the file is not linked to any particular simulation so it seems like it can be out of sync. 

In general (not related to the fields bug) I noticed that if I start a sim in Player from Twedit it is OK. If I open another sim in Twedit and launch it in Player player runs the new sim but the player window still has the old sim's name. If I restart the sim in Player it runs the first sim and not the most recently run sim.

**Comment by jpsluka** [comment] 2020-03-26 19:25
I see that the sqlite file at;
C:/Users/{USERNAME}/.compucell3d_py3/_settings.sqlite
Includes things about the most recently run sim including windows and field names. Shouldn't that info only be in the Project specif _settings.sqlite file?

**Comment by jpsluka** [comment] 2020-04-02 14:23
Here is a "typical" _seeting.sqlite file from the ..\.compucell3d_py3\ folder.
[_settings.zip](https://github.com/CompuCell3D/CompuCell3D/files/4421599/_settings.zip)
It contains a great deal of info about the last simulation run including;
Field names and min m

1. ax ranges (in FieldParams)
2. Screen shot and screen update frequencies
3. Screenshot_x and _y width

These should not be here since they should be contained in the **Projects** _settings.sqlite file. Really the only thing in this file should be the **default** parameters (copied from the template buried down in the CC3D source directories) and an up to date list of the recent simulations.

**Comment by jpsluka** [comment] 2020-04-04 20:11
Here is another example where this sqlite file causes problems.
1. Was running a CC3D project with an external monitor attached to my laptop. The CC3D window was on the second monitor.
2. Disconnected the external monitor. 
3. Created a new, unrelated project in Twedit++
4. Launch the new project to Player from Twedit++
    -> CC3D window is not visible (presumably it is off where the now not attached monitor was)
5. Delete the sqlite file in C:\Users\Jim Sluka\.compucell3d_py3 folder
6 Launch Player from Twedit++ and the Player window is visible.

The only thing in the .compucell3d_py3/_settings.sqlite should be the recent file list. No info from the last run should be in this file.

**Comment by maciekswat** [comment] 2020-04-12 01:04
Indeed this is what happens. Need to fix this bug

> 
> 
> Here is another example where this sqlite file causes problems.
> 
>     1. Was running a CC3D project with an external monitor attached to my laptop. The CC3D window was on the second monitor.
> 
>     2. Disconnected the external monitor.
> 
>     3. Created a new, unrelated project in Twedit++
> 
>     4. Launch the new project to Player from Twedit++
>        -> CC3D window is not visible (presumably it is off where the now not attached monitor was)
> 
>     5. Delete the sqlite file in C:\Users\Jim Sluka.compucell3d_py3 folder
>        6 Launch Player from Twedit++ and the Player window is visible.
> 
> 
> The only thing in the .compucell3d_py3/_settings.sqlite should be the recent file list. No info from the last run should be in this file.

**Comment by jpsluka** [comment] 2020-07-12 21:51
Will these changes fix the problem with player incorrectly reloading the configuration at the start of every run within a particular Player session?

**Comment by CompuCell3D** [comment] 2020-07-12 22:17
I think so. Worked in my tests and now entire layout is being saved including plots and steering panel.

**Comment by maciekswat** [comment] 2023-04-01 19:31
Closing this issue. Looks like it has been fixed

**Closed by maciekswat** 2023-04-01 19:31 UTC
