### ISSUE TITLE
File lock issues on clusters

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#166] opened 2019-11-13 18:20 UTC
Locks between multiple batch processes on the same compute node interfere. 

Parameter scan could make the batch run folders and then run the simulations to avoid it

**Comment by CompuCell3D** [comment] 2019-11-17 02:27
Do we know if this is due to file lock that is placed when simulaiton code is accessed or it is due to some other reason. What would be the steps to recreate this problem?

**Comment by tjsego** [comment] 2019-11-17 23:48
I was able to reproduce a file access issue on Windows 8.1 when attempting to run parallel command line executions. See https://github.com/CompuCell3D/CompuCell3D/commit/3e39d40f9b77feacfd48e8bfadd0692afb1efe1b

**Comment by tjsego** [comment] 2019-11-18 09:50
Improvement from https://github.com/CompuCell3D/CompuCell3D/commit/3e39d40f9b77feacfd48e8bfadd0692afb1efe1b: https://github.com/CompuCell3D/CompuCell3D/commit/f8a4355f9bb6c684b0a5b279a7eda6111ee53c0f

**Comment by tjsego** [comment] 2019-11-18 15:39
I could produce an access error to output from envVarSanitizer.py when making multiple parallel calls to runScript.bat on Windows. See https://github.com/CompuCell3D/CompuCell3D/commit/0b8e0d79854561ac31c0c000a0daf01bb1b8bf36 for a fix that seems to resolve parallel startup issues.

**Comment by JulianoGianlupi** [comment] 2020-02-15 16:50
So, I've managed to encounter this bug on my home machine. I was doing a scan of 4,320‬ iterations and the lock happened on iteration 2254. I was running 6 simultaneous simulations. So I feel that this bug is a matter of coincidence.

I am on the update_mot_plug branch as 

[persistent_bias.zip](https://github.com/CompuCell3D/CompuCell3D/files/4208753/persistent_bias.zip)


![image](https://user-images.githubusercontent.com/35964356/74591734-64c72080-4fe8-11ea-84a0-0c95422728b0.png)

**Comment by JulianoGianlupi** [comment] 2020-02-15 16:59
I wasn't able to see the bug happening live

**Comment by maciekswat** [comment] 2023-04-01 19:38
We have changed how we run parameter scans now and it also looks like this issue has been fixed. Closing for now

**Closed by maciekswat** 2023-04-01 19:38 UTC
