### ISSUE TITLE
Player <Tools> <Configuration> should update the _settings.sqlite file when the dialog is exited.

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#470] opened 2021-08-04 14:39 UTC
Player <Tools> <Configuration> should update the _settings.sqlite file when the dialog is exited.

People generally have trouble getting the Player configuration to propagate form run to run. It would help if the _settings.sqlite was updated on exiting from the Configuration dialog.

That won't catch changes in the window layout but it should catch all the changes in cell colors, field display limits etc.

**Comment by CompuCell3D** [comment] 2021-08-14 20:03
That make sense. Now _settings.sqlite is being updated when users press stop button but I agree it should also be updated when users exit Configuration dialog. Is this what you have noticed?

**Comment by CompuCell3D** [comment] 2021-08-14 21:02
@jpsluka Colors are actually saved in the way you described - user changes color for cell type clicks OK to close dialog and at that momeent the settings are written to  _settings.sqllite for a given simulation.

**Comment by CompuCell3D** [comment] 2021-08-14 22:11
Jim, if we could try to replicate this issue I would be happy to fix it. For now I will leave it open because based on my analysis CC3D works as designed - but we can certainly fix issues like that if indeed they exist

**Comment by jpsluka** [comment] 2021-08-15 18:26
I just checked and it looks like cell colors, field limits and screen shot frequency (at least) all do get updated with settings is closed. So the problems with saving screen shots must be else where. Also odd that it takes 10+ seconds to close the settings dialog, it looks like Player is repetitively writing the sqlite file? 

Can mark this issue as closed.

**Comment by CompuCell3D** [comment] 2021-09-04 20:12
closing the issue for now

**Closed by CompuCell3D** 2021-09-04 20:12 UTC
