### ISSUE TITLE
Need Twedit tools for building paramter scans

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#435] opened 2021-04-20 16:55 UTC
The previous tool for creating a parameter scan is gone. Adding a scan requires manually creating the json, adding the json file, with the correct syntax, into the .cc3d file, etc.

There isn't an option in the "Add resource..." function for adding a parameter scan json file.

Also, it appears that the json file name is hardcoded as "ParameterScanSpecs.json".
If you uses a different name and add that name into the .cc3d file it doesn't work.

<ParameterScan Type="ParameterScan">Simulation/ParameterScanSpecs.json</ParameterScan>

**Comment by CompuCell3D** [comment] 2021-04-21 03:15
You are right. This is all by design. I meant to add a GUI for parameter scan configuration but it got pushed back in priority. We can definitely add a GUI. I think json syntax is much simpler than previous XML-based specification but if you think having a GUI for configuring param scans is useful we can add it

**Comment by jpsluka** [comment] 2021-04-21 15:13
Don't necessarily need a gui like the one we had before but do need a simple widget in Twedit that:
1. Adds the json file (perhaps with example code and comments on how to use)
2. Adds the json file name into the .cc3d (this is currently lacking and is not documented anywhere)

BTW, can you confirm that the json file's name is actually hard coded and what is listed in the .cc3d file is ignored?

**Comment by jpsluka** [comment] 2021-04-21 15:40
It appears that in the .cc3d file you must have
   <ParameterScan Type="ParameterScan">Simulation/ParameterScanSpecs.json</ParameterScan>

and the json file name must be ParameterScanSpecs.json. Changing the file name fails, Even if you both rename the json file and change the entry in the .cc3d. Omitting the line from the .cc3d file fails.

**Comment by CompuCell3D** [comment] 2021-04-25 19:48
it is hardcoded

**Comment by jpsluka** [comment] 2021-04-26 19:20
If it is hard coded then that should be stated in the documentation. Is the line in the .cc3d file required at all?

**Comment by CompuCell3D** [comment] 2021-05-22 17:46
I think it is mentioned in the documentation and no it is not required but I think a better solution is to do what we did before - include stub in .cc3d. I have added it along with few other GUI tools for configuring param scan

**Comment by CompuCell3D** [comment] 2021-05-22 17:47
PR has been issued. New release will have GUI-configurable Parameter Scans. Adding new issue to write gui-based parameter scans documentation and closing this issue. Thanks @jpsluka  for bringing it up

**Closed by CompuCell3D** 2021-05-22 17:47 UTC
